[package]
name = "pulse"
version = "0.1.0"
edition = "2021"
categories = ["game-engines", "rendering"]
description = "Ambitious game engine in the very early stages of development"
license = "MIT"
readme = "README.md"
repository = "https://github.com/rosiebye/pulse"
publish = false

[dependencies]
